name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Jest tests
        run: npm test
    # - name: Set up Java 17
    #   uses: actions/setup-java@v4
    #   with:
    #     distribution: 'temurin'
    #     java-version: '17'

    # - name: Compile Java files -source and test
    #   run: |
    #     mkdir -p bin
    #     javac -cp "lib/*" -d bin $(find src tests -name "*.java")

    # - name: Run JUnit Tests
    #   run: |
    #     java -cp "bin:lib/*" org.junit.runner.JUnitCore CalculatorTest
