name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    uses: ./.github/workflows/tests.yml

  deploy:
    needs: test
    uses: ./.github/workflows/deploy.yml
