name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write # Autoriser l'écriture dans le repository
  issues: write # Si vous devez modifier des issues
  pull-requests: write # Si vous avez besoin de manipuler des pull requests

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  deploy:
    needs: tests
    uses: ./.github/workflows/deploy.yml
